name: Tests

on:
  push:
  pull_request:


jobs:
  tests:
    name: Compile and Run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bug: [
          ["c1-dead-lock-sdspi", "trace.vcd"], 
          ["c2-producer-consumer-mismatch-optimus", "optimus_produder_consumer.fst"],
          ]
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get install -y verilator  qemu-utils
    - name: check versions
      run: verilator --version
    - name: make sim
      run: |
        cd ${{ matrix.bug[0] }}
        make
        make sim
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.bug[0] }}_${{ matrix.bug[1] }}
        path: ${{ matrix.bug[0] }}/${{ matrix.bug[1] }}

